// The eight residents.
//
// Each one carries three separate things: a `bio` that gets handed to the model
// as a system prompt, a `schedule` that decides where their body is, and a
// `voice` the offline brain uses to put words in their mouth when no model is
// loaded. The last one is why the town still talks on a machine with no WebGPU.
//
// Schedule entries are `{ h, at, doing }`, sorted by hour; the entry in force is
// the last one whose hour has passed, wrapping at midnight.

export const CAST = [
  {
    id: 'rosa',
    name: 'Rosa Quill',
    role: 'baker',
    home: 'home-rosa',
    work: 'kettle',
    color: '#e8734a',
    hair: '#5a3222',
    skin: '#f1c49a',
    bio: 'Rosa Quill runs the Kettle, the café on the square. She is warm, incurably nosy, and remembers what everyone ordered and who they came in with. She thinks a rumour is a kind of weather: not her fault, and worth discussing.',
    traits: ['warm', 'nosy', 'never forgets a face'],
    schedule: [
      { h: 0, at: 'home-rosa', doing: 'asleep' },
      { h: 5, at: 'kettle', doing: 'lighting the ovens' },
      { h: 9, at: 'kettle', doing: 'working the counter' },
      { h: 13, at: 'market', doing: 'arguing about the price of flour' },
      { h: 14, at: 'kettle', doing: 'the afternoon bake' },
      { h: 18, at: 'square', doing: 'giving away the last of the buns' },
      { h: 20, at: 'home-rosa', doing: 'sitting with the radio on' },
      { h: 23, at: 'home-rosa', doing: 'asleep' },
    ],
    voice: {
      open: [
        'There you are, {them}.',
        'Sit down a minute, {them}.',
        'I was going to come and find you, {them}.',
        'Don’t tell me you’re not eating again.',
      ],
      reply: [
        'Mm. That’s about what I’d have said.',
        'Well. That explains the state of you.',
        'You know who else said that? Someone did.',
        'I’ll tell you what I think, and I think you know already.',
      ],
      gossip: ['Between us — {rumor}', 'You didn’t hear it from me, but {rumor}', 'They’re all saying {rumor}'],
      hear: ['Are they really.', 'Now that I did not know.', 'Hm. I’ll be keeping an ear out.'],
      idle: ['Ovens don’t light themselves.', 'Everything tastes better in the cold.', 'One more tray.'],
    },
  },
  {
    id: 'bo',
    name: 'Bo Tran',
    role: 'tinkerer',
    home: 'home-bo',
    work: 'workshop',
    color: '#4a9fd8',
    hair: '#231a18',
    skin: '#d8a074',
    bio: 'Bo Tran fixes things in the workshop on the east lane, usually by taking them entirely apart first. He talks in half-sentences because the other half is still being worked out. He is kind and about forty percent present.',
    traits: ['distracted', 'gentle', 'always mid-thought'],
    schedule: [
      { h: 0, at: 'home-bo', doing: 'asleep' },
      { h: 7, at: 'home-bo', doing: 'eating standing up' },
      { h: 8, at: 'workshop', doing: 'taking something apart' },
      { h: 12, at: 'kettle', doing: 'forgetting to order anything' },
      { h: 13, at: 'workshop', doing: 'putting it back together, mostly' },
      { h: 19, at: 'square', doing: 'walking it off' },
      { h: 21, at: 'home-bo', doing: 'drawing on the tablecloth' },
      { h: 23, at: 'home-bo', doing: 'asleep' },
    ],
    voice: {
      open: [
        'Oh — {them}. Good. I had a — hold on.',
        '{them}. Question. Sorry. Hello first.',
        'Right, you’ll know this.',
        'Don’t move, I’ve nearly got it.',
      ],
      reply: [
        'Hm. Yes. No. Say the middle bit again.',
        'That would explain the noise.',
        'I had that thought at about four in the morning.',
        'It’s not the spring. I thought it was the spring.',
      ],
      gossip: ['Somebody told me — {rumor} — is that a real thing?', 'Apparently {rumor}. I don’t know what to do with that.'],
      hear: ['Huh.', 'That’s mechanically unlikely.', 'Say that again slowly.'],
      idle: ['Where did I put the small one.', 'It worked yesterday.', 'Two screws left over. Fine.'],
    },
  },
  {
    id: 'nadia',
    name: 'Nadia Okonjo',
    role: 'librarian',
    home: 'home-nadia',
    work: 'library',
    color: '#8b6fc4',
    hair: '#1a1210',
    skin: '#8c5a3c',
    bio: 'Nadia Okonjo keeps the reading room. She is precise, funny in a way that takes people a second, and she disapproves of rumours on principle — which does not stop her from being extremely well informed.',
    traits: ['precise', 'dry', 'sceptical'],
    schedule: [
      { h: 0, at: 'home-nadia', doing: 'asleep' },
      { h: 7, at: 'home-nadia', doing: 'reading the last of last night' },
      { h: 8, at: 'library', doing: 'opening up' },
      { h: 12, at: 'kettle', doing: 'a coffee and a look at everyone' },
      { h: 13, at: 'library', doing: 'shelving' },
      { h: 18, at: 'pond', doing: 'a walk to the water' },
      { h: 20, at: 'home-nadia', doing: 'at the desk by the window' },
      { h: 23, at: 'home-nadia', doing: 'asleep' },
    ],
    voice: {
      open: [
        '{them}. You look like a person with a question.',
        'I have four minutes and then I have shelves.',
        'Before you say it — is it true?',
        'Good. Someone sensible.',
      ],
      reply: [
        'That is a claim. Where did it come from?',
        'Mm. I’d want that in writing.',
        'It’s a nice story. Nice stories usually are.',
        'Fine. I’ll allow it.',
      ],
      gossip: ['I don’t deal in this, but: {rumor}', 'For the record I think it’s nonsense — {rumor}'],
      hear: ['Who told you that?', 'Source?', 'I’ll believe it when the shelf says so.'],
      idle: ['Someone has reshelved this wrong.', 'Quiet. Finally.', 'Three overdue. Three.'],
    },
  },
  {
    id: 'milo',
    name: 'Milo Fen',
    role: 'child',
    home: 'home-milo',
    work: 'square',
    color: '#f2c14e',
    hair: '#c9822a',
    skin: '#f4d0ae',
    bio: 'Milo Fen is nine. He believes almost everything he is told and repeats it immediately and at volume. He is the fastest way for anything to travel across Simville.',
    traits: ['credulous', 'loud', 'relentlessly curious'],
    schedule: [
      { h: 0, at: 'home-milo', doing: 'asleep' },
      { h: 7, at: 'home-milo', doing: 'not getting dressed' },
      { h: 9, at: 'library', doing: 'being quiet, briefly' },
      { h: 11, at: 'square', doing: 'running a lap of the square' },
      { h: 13, at: 'kettle', doing: 'hoping for a free bun' },
      { h: 15, at: 'pond', doing: 'looking for the big fish' },
      { h: 18, at: 'square', doing: 'telling everyone everything' },
      { h: 20, at: 'home-milo', doing: 'refusing to go to bed' },
      { h: 22, at: 'home-milo', doing: 'asleep' },
    ],
    voice: {
      open: [
        '{them}! {them}! Guess what.',
        'Is it true? It’s true, isn’t it.',
        'I’ve been looking for you all day.',
        'Can I ask you something enormous?',
      ],
      reply: [
        'Whoa.',
        'That’s what I SAID.',
        'But how though?',
        'I’m telling everyone.',
      ],
      gossip: ['GUESS WHAT. {rumor}', 'Okay so {rumor} and I saw it basically', 'Everyone knows {rumor} now'],
      hear: ['NO.', 'I knew it!', 'Wait till I tell Oma.'],
      idle: ['Nothing ever happens here. Except everything.', 'That fish is real.', 'One more lap.'],
    },
  },
  {
    id: 'oma',
    name: 'Oma Greer',
    role: 'keeper of the pond',
    home: 'home-oma',
    work: 'pond',
    color: '#5fa878',
    hair: '#cfd2d0',
    skin: '#e6c3a3',
    bio: 'Oma Greer is retired and looks after the pond, which nobody asked her to do. She speaks slowly and lands somewhere unexpected. She has outlived three versions of most of the town gossip.',
    traits: ['unhurried', 'oblique', 'has seen this before'],
    schedule: [
      { h: 0, at: 'home-oma', doing: 'asleep' },
      { h: 6, at: 'pond', doing: 'clearing the reeds' },
      { h: 10, at: 'bench', doing: 'sitting with the water' },
      { h: 13, at: 'kettle', doing: 'the long lunch' },
      { h: 15, at: 'pond', doing: 'feeding whatever turns up' },
      { h: 18, at: 'square', doing: 'the evening round' },
      { h: 20, at: 'home-oma', doing: 'the last of the light' },
      { h: 22, at: 'home-oma', doing: 'asleep' },
    ],
    voice: {
      open: [
        'Sit, {them}. The water’s doing something.',
        'You walk like your father did.',
        'Give me a minute of it.',
        'Ah. The day sends someone.',
      ],
      reply: [
        'That’s one way for it to go.',
        'We had that in seventy-one. Different name.',
        'Hm. Hold onto that.',
        'The pond doesn’t mind either way.',
      ],
      gossip: ['They’re saying {rumor}. They said something like it before.', 'Word is {rumor}. Word usually is.'],
      hear: ['Is that the shape of it.', 'Someone always starts these.', 'Mm.'],
      idle: ['Reeds again.', 'Cold coming.', 'Still there, then.'],
    },
  },
  {
    id: 'yusef',
    name: 'Yusef Bright',
    role: 'trader',
    home: 'home-yusef',
    work: 'market',
    color: '#d94f6e',
    hair: '#2c1a14',
    skin: '#c08050',
    bio: 'Yusef Bright sells things in the market hall and on the square. Everything he describes is slightly larger and more urgent than it is. He is generous, exhausting, and genuinely good at his job.',
    traits: ['loud', 'embellishes', 'generous'],
    schedule: [
      { h: 0, at: 'home-yusef', doing: 'asleep' },
      { h: 6, at: 'market', doing: 'setting out the good stuff at the front' },
      { h: 9, at: 'square', doing: 'working the stall' },
      { h: 13, at: 'kettle', doing: 'holding court over coffee' },
      { h: 14, at: 'square', doing: 'the afternoon push' },
      { h: 18, at: 'market', doing: 'packing up slowly' },
      { h: 20, at: 'home-yusef', doing: 'counting it twice' },
      { h: 23, at: 'home-yusef', doing: 'asleep' },
    ],
    voice: {
      open: [
        '{them}! The very person.',
        'Now — before you say no.',
        'I’m glad you’re here, I’m glad, sit.',
        'Two minutes. Two. That’s all I want.',
      ],
      reply: [
        'See, that’s exactly what I said, only better.',
        'Ha! No. Well. Partly.',
        'You’re a hard person, and I respect it.',
        'Everyone’s talking about it. Everyone.',
      ],
      gossip: ['Listen — {rumor}. I heard it first.', 'It’s all over town: {rumor}', 'They’re saying {rumor}, and I believe every word.'],
      hear: ['I KNEW there was something.', 'Right. Right. That’s worth something, that.', 'Who else knows?'],
      idle: ['Best prices in the county. The only prices in the county.', 'Slow morning. Slow.', 'Nearly sold the lot.'],
    },
  },
  {
    id: 'pia',
    name: 'Pia Sørensen',
    role: 'painter',
    home: 'studio',
    work: 'studio',
    color: '#3fb3a6',
    hair: '#e0d6c2',
    skin: '#eecdb0',
    bio: 'Pia Sørensen paints in the studio on the west edge and works at dawn because the light is better and nobody is talking yet. She watches more than she speaks, and what she says tends to arrive sideways.',
    traits: ['observant', 'oblique', 'up before anyone'],
    schedule: [
      { h: 0, at: 'studio', doing: 'asleep' },
      { h: 4, at: 'pond', doing: 'watching the light arrive' },
      { h: 7, at: 'studio', doing: 'painting while it lasts' },
      { h: 12, at: 'kettle', doing: 'not really eating' },
      { h: 13, at: 'studio', doing: 'scraping most of it off' },
      { h: 17, at: 'square', doing: 'looking at people' },
      { h: 19, at: 'studio', doing: 'starting again' },
      { h: 23, at: 'studio', doing: 'asleep' },
    ],
    voice: {
      open: [
        'Stand there. No — there. Thank you.',
        'You’ve got the evening on you.',
        'I saw something this morning.',
        'Don’t talk for a second.',
      ],
      reply: [
        'That’s not the colour of it.',
        'Say it the way you said it the first time.',
        'Everyone looks like something. You look like a Tuesday.',
        'Mm. I’ll use that.',
      ],
      gossip: ['There’s a thing going round. {rumor}', 'People have been saying {rumor}. It’s in their faces.'],
      hear: ['That’s a good shape for a story.', 'Someone wanted that to be true.', 'Hm.'],
      idle: ['The light went.', 'Too much green.', 'Start again.'],
    },
  },
  {
    id: 'ray',
    name: 'Ray Alder',
    role: 'constable',
    home: 'watch',
    work: 'watch',
    color: '#6d7f95',
    hair: '#3a3a3a',
    skin: '#d9ab84',
    bio: 'Ray Alder is the constable and takes everything at face value, which in a town this size is a full-time job. He dislikes rumours because they generate paperwork, and he writes down almost everything.',
    traits: ['literal', 'dutiful', 'allergic to hearsay'],
    schedule: [
      { h: 0, at: 'watch', doing: 'asleep' },
      { h: 6, at: 'watch', doing: 'the morning log' },
      { h: 8, at: 'square', doing: 'the rounds' },
      { h: 12, at: 'kettle', doing: 'a coffee, standing' },
      { h: 13, at: 'market', doing: 'the rounds again' },
      { h: 17, at: 'pond', doing: 'checking the far side' },
      { h: 19, at: 'watch', doing: 'writing it all down' },
      { h: 22, at: 'watch', doing: 'asleep' },
    ],
    voice: {
      open: [
        'Evening. Anything to report?',
        '{them}. A word.',
        'I’ll be brief.',
        'I’m told you were there.',
      ],
      reply: [
        'Noted.',
        'That’s hearsay and you know it.',
        'I’ll need that again, with a time on it.',
        'Right. And who saw that?',
      ],
      gossip: ['I’m told, and I’m only repeating it: {rumor}', 'There’s a report going round that {rumor}'],
      hear: ['That’ll be nothing.', 'I’ll look into it.', 'Paperwork.'],
      idle: ['All quiet.', 'Nothing in the book.', 'Lamp’s out again.'],
    },
  },
]

// The starting web of who thinks what of whom. Everyone knows everyone in a
// town this size; the sim moves these numbers around from there.
export const INITIAL_TIES = {
  'rosa:nadia': 0.5, 'rosa:yusef': 0.6, 'rosa:milo': 0.7, 'rosa:bo': 0.4,
  'nadia:ray': 0.5, 'nadia:milo': 0.3, 'nadia:yusef': -0.2,
  'bo:oma': 0.5, 'bo:milo': 0.6, 'bo:pia': 0.3,
  'milo:oma': 0.7, 'milo:yusef': 0.5,
  'oma:pia': 0.6, 'oma:ray': 0.3,
  'yusef:ray': -0.3, 'yusef:pia': 0.2,
  'pia:ray': 0.1,
}

export function tieKey(a, b) {
  return a < b ? `${a}:${b}` : `${b}:${a}`
}

// The rumours the player can let loose. The first one is planted at dawn so the
// town always has something in the air.
export const SEED_RUMOURS = [
  'there’s a fish in the pond that grants one wish',
  'the Kettle is closing at the end of the month',
  'someone has been moving the bench at night',
  'a stranger was seen on the east lane before dawn',
  'the well has gone sweet again',
  'Bo has built something that shouldn’t work, and it works',
]
