// The einstein monotile — exact integer geometry.
//
// The hat is eight kites of the deltoidal trihexagonal grid, so *every* legal
// placement of it is a union of eight cells of one fixed lattice. That makes
// overlap, adjacency and "where could this go?" pure integer set arithmetic —
// no epsilons, no floating-point snapping, no drift after two hundred tiles.
//
// The lattice
// -----------
// Points live in a triangular lattice L with basis e1 = (1,0), e2 = (½, √3/2):
//
//     cart(a, b) = (a + b/2, b·√3/2)          |(a,b)|² = a² + ab + b²
//
// Hexagons of circumradius 2 tile the plane; their centres form the index-12
// sublattice generated by (2,2) and (−2,4). Each hexagon splits into six kites.
// Kite k of the hexagon centred at C is the quad
//
//     [ C, M(k−1), V(k), M(k) ]      V(j) = C + 2·D[j]   M(j) = C + D[j] + D[j+1]
//
// Its two C→M sides have length √3 (the *long* pair) and its two M→V sides
// length 1 (the *short* pair) — the 60°–90°–120°–90° kite the paper builds the
// hat from. That distinction matters downstream: neighbourKeys() returns the two
// long-side neighbours first, and the river rule only binds across those.
//
// The hat itself
// --------------
// HAT_KITES below was derived, not guessed: Craig Kaplan's `hatviz` gives the
// canonical 13-gon outline, and the eight kites whose union reproduces that
// outline edge-for-edge are the ones listed. See the header of tiles.js for the
// sanity checks that fall out of it (area = 8√3, 12 distinct orientations,
// ~1/7 of a greedily packed patch coming out reflected).

export const R3 = Math.sqrt(3)

/** Lattice point → world XZ (world units == lattice units). */
export function cart(a, b) {
  return [a + b / 2, (b * R3) / 2]
}

/** The six unit directions of L, in counter-clockwise order. */
export const D = [
  [1, 0],
  [0, 1],
  [-1, 1],
  [-1, 0],
  [0, -1],
  [1, -1],
]

// A kite cell (a, b, k) packed into one small integer, so the board can be a
// Set/Map of numbers rather than of strings. ±1024 of lattice room is roughly a
// thousand tiles in every direction — far past anything a game reaches.
export const KEY = (a, b, k) => ((a + 1024) << 15) | ((b + 1024) << 3) | k
export const KEY_A = (key) => ((key >> 15) & 2047) - 1024
export const KEY_B = (key) => ((key >> 3) & 4095) - 1024
export const KEY_K = (key) => key & 7

/** The hat, as eight kite cells [hexCentreA, hexCentreB, kiteIndex]. */
export const HAT_KITES = [
  [0, 0, 0],
  [0, 0, 1],
  [0, 0, 4],
  [0, 0, 5],
  [4, -2, 1],
  [4, -2, 2],
  [2, 2, 3],
  [2, 2, 4],
]

// --- symmetry ---------------------------------------------------------------

// Both generators map L to itself *and* map hexagon centres to hexagon centres,
// which is what makes the twelve orientations exact.
const rot60 = (a, b) => [-b, a + b] // 60° about a hexagon centre
const mirror = (a, b) => [a + b, -b] // reflection in the e1 axis

/**
 * The twelve orientations of the hat: six rotations × two chiralities. The hat
 * has no symmetry of its own, so all twelve are genuinely distinct — which is
 * also why a tiling needs both chiralities.
 */
export const ORIENTS = []
for (let flip = 0; flip < 2; flip++) {
  for (let r = 0; r < 6; r++) ORIENTS.push({ r, flip, index: ORIENTS.length })
}

function applyOrient(o, a, b, k) {
  let p = [a, b]
  if (o.flip) {
    p = mirror(p[0], p[1])
    k = (6 - k) % 6
  }
  for (let i = 0; i < o.r; i++) {
    p = rot60(p[0], p[1])
    k = (k + 1) % 6
  }
  return [p[0], p[1], k]
}

/** ORIENT_KITES[o] = the hat's eight cells in orientation o, untranslated. */
export const ORIENT_KITES = ORIENTS.map((o) => HAT_KITES.map(([a, b, k]) => applyOrient(o, a, b, k)))

// --- per-cell geometry ------------------------------------------------------

/** The kite's four corners in lattice coordinates: centre, mid, vertex, mid. */
export function kiteCorners(a, b, k) {
  const dm = D[(k + 5) % 6]
  const dk = D[k]
  const dp = D[(k + 1) % 6]
  return [
    [a, b],
    [a + dm[0] + dk[0], b + dm[1] + dk[1]],
    [a + 2 * dk[0], b + 2 * dk[1]],
    [a + dk[0] + dp[0], b + dk[1] + dp[1]],
  ]
}

/** The kite's centroid in world XZ. Used for props, labels and picking. */
export function kiteCentre(a, b, k) {
  const c = kiteCorners(a, b, k)
  let x = 0
  let y = 0
  for (const [p, q] of c) {
    const [cx, cy] = cart(p, q)
    x += cx
    y += cy
  }
  return [x / 4, y / 4]
}

/**
 * The four edge-neighbours of a kite cell, as packed keys, in a fixed order:
 *   0: the next kite round the same hexagon      — shares the LONG side C→M(k)
 *   1: the previous kite round the same hexagon  — shares the LONG side C→M(k−1)
 *   2: across the hexagon edge, on the M(k−1)→V(k) side — a SHORT side
 *   3: across the hexagon edge, on the V(k)→M(k) side   — a SHORT side
 *
 * Two properties everything downstream leans on: the relation is symmetric, and
 * the long-side neighbours come first, so `j < 2` is the whole test for "do the
 * two kites share a hexagon?" — which is what the river rule turns on.
 */
export function neighbourKeys(a, b, k, out = []) {
  const dm = D[(k + 5) % 6]
  const dk = D[k]
  const dp = D[(k + 1) % 6]
  out[0] = KEY(a, b, (k + 1) % 6)
  out[1] = KEY(a, b, (k + 5) % 6)
  out[2] = KEY(a + 2 * (dm[0] + dk[0]), b + 2 * (dm[1] + dk[1]), (k + 2) % 6)
  out[3] = KEY(a + 2 * (dk[0] + dp[0]), b + 2 * (dk[1] + dp[1]), (k + 4) % 6)
  return out
}

// --- placements -------------------------------------------------------------

/** The same eight cells as packed keys, in slot order. */
export function placementKeys(orient, ta, tb, out = new Array(8)) {
  const base = ORIENT_KITES[orient]
  for (let i = 0; i < 8; i++) out[i] = KEY(base[i][0] + ta, base[i][1] + tb, base[i][2])
  return out
}

/** A stable id for a placement, so candidate lists can be de-duplicated. */
export const placementId = (orient, ta, tb) => orient * 4194304 + ((ta + 1024) << 11) + (tb + 1024)

/**
 * Every placement that overlaps nothing and touches the existing patch along at
 * least one kite edge.
 *
 * Because a hat is a union of kite cells, aligning any one of its eight cells
 * onto a given empty cell *fixes the translation completely* — so instead of
 * searching the plane we walk the frontier. For each empty cell touching the
 * patch, each of the twelve orientations, and each of the hat's slots whose
 * kite index matches that cell (8/6 ≈ 1.3 of them on average), there is exactly
 * one translation to test. That is ~16 trial placements per frontier cell:
 * about 1.5 ms around a 300-tile patch, once per turn.
 */
export function candidatePlacements(occupied) {
  const frontier = new Set()
  const nb = []
  for (const key of occupied) {
    const a = KEY_A(key)
    const b = KEY_B(key)
    const k = KEY_K(key)
    neighbourKeys(a, b, k, nb)
    for (let i = 0; i < 4; i++) if (!occupied.has(nb[i])) frontier.add(nb[i])
  }

  const out = []
  const seen = new Set()
  for (const fkey of frontier) {
    const fa = KEY_A(fkey)
    const fb = KEY_B(fkey)
    const fk = KEY_K(fkey)
    for (let o = 0; o < 12; o++) {
      const base = ORIENT_KITES[o]
      for (let i = 0; i < 8; i++) {
        if (base[i][2] !== fk) continue
        const ta = fa - base[i][0]
        const tb = fb - base[i][1]
        const id = placementId(o, ta, tb)
        if (seen.has(id)) continue
        seen.add(id)
        let free = true
        for (let j = 0; j < 8; j++) {
          if (occupied.has(KEY(base[j][0] + ta, base[j][1] + tb, base[j][2]))) {
            free = false
            break
          }
        }
        if (free) out.push({ o, ta, tb, id })
      }
    }
  }
  return out
}

/**
 * The hat's outline for one orientation, in lattice-cartesian points: the union
 * boundary of its eight kites, walked as a single loop. Collinear runs are kept,
 * because the hat genuinely has one side of length 2 that reads as two collinear
 * unit sides — 14 points for a 13-sided tile.
 */
export function orientOutline(orient) {
  const dirEdges = new Map()
  for (const [a, b, k] of ORIENT_KITES[orient]) {
    const poly = kiteCorners(a, b, k)
    for (let i = 0; i < 4; i++) {
      const p = poly[i]
      const q = poly[(i + 1) % 4]
      const fwd = `${p[0]},${p[1]}>${q[0]},${q[1]}`
      const rev = `${q[0]},${q[1]}>${p[0]},${p[1]}`
      if (dirEdges.has(rev)) dirEdges.delete(rev)
      else dirEdges.set(fwd, [p, q])
    }
  }
  const next = new Map()
  for (const [p, q] of dirEdges.values()) next.set(`${p[0]},${p[1]}`, q)
  const start = dirEdges.values().next().value[0]
  const loop = [start]
  let cur = next.get(`${start[0]},${start[1]}`)
  while (cur && (cur[0] !== start[0] || cur[1] !== start[1])) {
    loop.push(cur)
    cur = next.get(`${cur[0]},${cur[1]}`)
  }
  return loop.map(([a, b]) => cart(a, b))
}

// --- picking ----------------------------------------------------------------

/**
 * World XZ → the kite cell containing it. Inverts the lattice rather than
 * raycasting geometry: find the nearest hexagon centre, then read off which of
 * its six wedges the point falls in.
 */
export function cellAt(x, z) {
  // World → lattice coordinates (invert cart()).
  const b = (2 * z) / R3
  const a = x - b / 2
  // Nearest hexagon centre. Centres are the sublattice ⟨(2,2), (−2,4)⟩; in the
  // (m, n) coordinates of that basis a point is (a,b) = m(2,2) + n(−2,4).
  const n = (b - a) / 6
  const m = (a + 2 * n) / 2
  let best = null
  let bestD = Infinity
  for (const [dm, dn] of NEAR) {
    const mm = Math.round(m) + dm
    const nn = Math.round(n) + dn
    const ca = 2 * mm - 2 * nn
    const cb = 2 * mm + 4 * nn
    const da = a - ca
    const db = b - cb
    const d = da * da + da * db + db * db
    if (d < bestD) {
      bestD = d
      best = [ca, cb, da, db]
    }
  }
  const [ca, cb, da, db] = best
  // Which 60° wedge of that hexagon? Kite k spans the wedge whose bisector is
  // the direction of corner k, i.e. angle 60k in lattice terms.
  const [px, py] = [da + db / 2, (db * R3) / 2]
  let ang = Math.atan2(py, px)
  if (ang < 0) ang += Math.PI * 2
  const k = Math.floor((ang + Math.PI / 6) / (Math.PI / 3)) % 6
  return [ca, cb, k]
}

const NEAR = [
  [0, 0],
  [1, 0],
  [-1, 0],
  [0, 1],
  [0, -1],
  [1, -1],
  [-1, 1],
]
