// Curated designs. Each preset is a partial override on top of the defaults, so
// a preset written today still loads after new controls are added.
//
// These are meant to be starting points with opinions, not a tidy sampler: the
// point of the lathe is that you grab one and push it somewhere else.
export const PRESETS = [
  {
    name: 'Monoline',
    params: { rdMode: 'ink', nbWeight: 15, nbCapAuto: false, nbCapStart: 'round', nbCapEnd: 'round' },
  },
  {
    name: 'Brush 楷書',
    params: {
      rdMode: 'ink',
      nbWeight: 30,
      nbContrast: 0.45,
      nbNibAngle: 38,
      nbPressIn: 0.3,
      nbPressOut: 0.55,
      nbHookFlare: 0.75,
      nbHVContrast: 0.3,
      nbCapAuto: true,
      stEntasis: 0.12,
      stTension: 0.15,
      rdBleed: 0.12,
    },
  },
  {
    name: 'Crown Shy',
    params: {
      rdMode: 'ink',
      nbWeight: 34,
      nbContrast: 0.2,
      syStrength: 0.55,
      syRadius: 0.09,
      syIterations: 8,
      syPerp: 0.7,
      syTrim: 0.14,
      syTrimReach: 0.09,
      syPreserveEnds: 0.35,
      syRelax: 0.3,
      nbCapAuto: false,
      nbCapStart: 'round',
      nbCapEnd: 'round',
    },
  },
  {
    name: 'Canopy Gap',
    params: {
      rdMode: 'component',
      nbWeight: 42,
      syStrength: 0.85,
      syRadius: 0.14,
      syIterations: 14,
      syPerp: 0.85,
      syTrim: 0.3,
      syTrimReach: 0.14,
      syOrderBias: 0.6,
      syGapTarget: 0.05,
      syRelax: 0.4,
      lyExplode: 0.12,
      nbCapAuto: false,
      nbCapEnd: 'round',
    },
  },
  {
    name: 'Modular Grid',
    params: {
      rdMode: 'ink',
      // Four directions means pure horizontals and verticals: the kanji is
      // rebuilt out of rectilinear elements, which is the whole idea.
      lyCellFit: 0.55,
      lyCellGutter: 0.05,
      lyCellAspect: 0.3,
      stAngleQuant: 0.8,
      stAngleSteps: 4,
      stStraighten: 0.9,
      stGridSnap: 0.25,
      stGridN: 12,
      ftFit: 'fit',
      ftSquareness: 0.5,
      nbWeight: 34,
      nbHVContrast: -0.2,
      nbCapAuto: false,
      nbCapStart: 'butt',
      nbCapEnd: 'butt',
    },
  },
  {
    name: 'Breathing Room',
    params: {
      rdMode: 'ink',
      wpEqualize: 0.9,
      wpBands: 22,
      wpSmooth: 0.5,
      syStrength: 0.3,
      syRadius: 0.07,
      syTrim: 0.07,
      nbWeight: 26,
      nbGrayNorm: 0.65,
    },
  },
  {
    name: 'Black Compression',
    params: {
      rdMode: 'ink',
      wpEqualize: -0.85,
      wpCenterEdge: 0.3,
      nbWeight: 46,
      nbGrayNorm: 0.9,
      nbHVContrast: 0.25,
      rdBleed: 0.3,
    },
  },
  {
    name: 'Radical Spotlight',
    params: {
      rdMode: 'component',
      lyRadicalScale: 1.45,
      lyRadicalWeight: 0.55,
      lyOtherScale: 0.82,
      lyExplode: 0.08,
      nbWeight: 26,
      rdHueSpread: 45,
    },
  },
  {
    name: 'Constructivist',
    params: {
      rdMode: 'ink',
      stAngleQuant: 0.8,
      stAngleSteps: 8,
      stStraighten: 0.85,
      stCrisp: 0.4,
      nbWeight: 22,
      nbHVContrast: -0.4,
      nbCapAuto: false,
      nbCapStart: 'butt',
      nbCapEnd: 'butt',
      ftFit: 'clamp',
      ftSquareness: 0,
    },
  },
  {
    name: 'Wet Ink',
    params: {
      rdMode: 'ink',
      nbWeight: 52,
      nbWobble: 0.45,
      nbWobbleFreq: 9,
      nbGrayNorm: 0.8,
      nbCapAuto: false,
      nbCapStart: 'bulb',
      nbCapEnd: 'bulb',
      nzTremor: 0.012,
      rdBleed: 0.55,
      rdGrain: 0.3,
    },
  },
  {
    name: 'Ribbon Order',
    params: { rdMode: 'ribbon', nbWeight: 42, nbContrast: 0.3, nbPressIn: 0.2, nbPressOut: 0.4, rdHueSpread: 210 },
  },
  {
    name: 'Vortex',
    params: { rdMode: 'order', frTwist: 0.5, frBarrel: 0.25, nbWeight: 30, nbPressOut: 0.4, rdHueSpread: 160 },
  },
  {
    name: 'Polar Bloom',
    params: {
      rdMode: 'order',
      frPolar: 0.8,
      frPolarArc: 300,
      frPolarInner: 0.28,
      nbWeight: 22,
      rdHueSpread: 300,
      ftFit: 'fit',
    },
  },
  {
    name: 'Tangled Garden',
    params: {
      rdMode: 'ink',
      nzField: 0.022,
      nzFieldScale: 5.5,
      nzFieldOctaves: 2,
      nzTremor: 0.008,
      nzTremorFreq: 9,
      syStrength: 0.5,
      syRadius: 0.075,
      syTrim: 0.12,
      syPerp: 0.6,
      nbWeight: 18,
      nbContrast: 0.4,
      nbPressOut: 0.4,
      stEntasis: 0.1,
    },
  },
  {
    name: 'Blueprint',
    params: { rdMode: 'wire', rdShowGrid: true, nbWeight: 20, rdInk: '#7fd6ff', rdAccent: '#ffd166' },
  },
  { name: 'Topographic', params: { rdMode: 'contour', rdContourStep: 7, nbWeight: 48 } },
  { name: 'Neon', params: { rdMode: 'neon', nbWeight: 16, nbHookFlare: 0.6, rdInk: '#ff5ea8', rdAccent: '#59f7d0' } },
  { name: 'Letterpress', params: { rdMode: 'letterpress', nbWeight: 38, rdGrain: 0.45, rdShadow: 0.35 } },
  { name: 'Halftone', params: { rdMode: 'dot', nbWeight: 46, rdHatchStep: 7 } },
  {
    name: 'Drunk Master',
    params: {
      rdMode: 'ink',
      nzWander: 0.028,
      nzWanderRot: 12,
      nzTremor: 0.026,
      nzTremorFreq: 6,
      nzEndpointJit: 0.05,
      nzOrderDecay: 0.7,
      nbWeight: 30,
      nbContrast: 0.5,
      nbPressOut: 0.5,
      stStraighten: -0.3,
    },
  },
  {
    name: 'Hairline Whisper',
    params: { rdMode: 'ink', nbWeight: 6, stTension: 0.5, ftFit: 'fit', ftMargin: 0.14, rdOpacity: 0.9 },
  },
  {
    name: 'Slab Machine',
    params: {
      rdMode: 'ink',
      stStraighten: 1,
      stTension: 0.2,
      nbWeight: 34,
      nbHVContrast: -0.35,
      nbCapAuto: false,
      nbCapStart: 'slab',
      nbCapEnd: 'slab',
      ftFit: 'fit',
      ftSquareness: 0.4,
    },
  },
  {
    name: 'Deep Fractal',
    params: { rdMode: 'ink', lyDepthScale: 0.42, lyCellFit: 0.4, nbDepthWeight: -0.5, nbWeight: 28, syStrength: 0.25 },
  },
  {
    name: 'X-Ray',
    params: { rdMode: 'xray', nbWeight: 40, rdOpacity: 0.4, rdHueSpread: 120, syStrength: 0.2 },
  },
]
